# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

#homeassistant:
#  packages: !include_dir_named packages

intent:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://0.0.0.0:9000"
    icon: mdi:docker
  vscode:
    title: "VSCode"
    url: "http://0.0.0.0:8443/"
    icon: mdi:microsoft-visual-studio-code
  esphome:
    title: "ESPHome"
    url: "http://0.0.0.0:6052"
    icon: mdi:chip
  zigbee2mqtt:
    title: "Zigbee2MQTT"
    url: "http://0.0.0.0:8080"
    icon: mdi:zigbee
  appdaemon:
    title: "appdaemon"
    url: "http://0.0.0.0:5050"
    icon: mdi:language-python
  rhasspy:
    title: "Rhasspy"
    url: "http://0.0.0.0:12101"
    icon: mdi:account-voice
