
panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://IP_ADDRESS:9000"
    icon: mdi:docker
  vscode:
    title: "VSCode"
    url: "http://IP_ADDRESS:8443/"
    icon: mdi:microsoft-visual-studio-code
  esphome:
    title: "ESPHome"
    url: "http://IP_ADDRESS:6052"
    icon: mdi:chip
  zigbee2mqtt:
    title: "Zigbee2MQTT"
    url: "http://IP_ADDRESS:8080"
    icon: mdi:zigbee

# my appologies, this is actually not required, just omit
#mqtt data
#mqtt:
# broker: IP_ADDRESS
# port: 1883
# client_id: home-assistant
# username: !secret mqtt_user
# password: !secret mqtt_pass
# discovery: true
# discovery_prefix: homeassistant
