# Home Assistant integration (MQTT discovery)
homeassistant: true

# Enable Web GUI, can just be "frontend: true"
frontend:
  # Optional, default 8080
  port: 8080
  # Optional, default 0.0.0.0
  host: 0.0.0.0

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://HOST_IP_ADDRESS'
  # MQTT server authentication, uncomment if required:
  # user: mqtt-user
  # password: mqtt-pass

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
